# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cypress/browsers:node12.16.1-chrome80-ff73

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/repo
          paths: [.]

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Source code linting
          command: npm run lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Unit testing
          command: npm test

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Create app bundle
          command: npm run build

  test-recipes-angularjs-ng-file-upload:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install dependencies
          command: npm install
          working_directory: recipes/angularjs-ng-file-upload
      - run:
          name: e2e suite for recipes/angularjs-ng-file-upload on Chrome
          command: npm run test:ci:chrome
          working_directory: recipes/angularjs-ng-file-upload
      - run:
          name: e2e suite for recipes/angularjs-ng-file-upload on Firefox
          command: npm run test:ci:firefox
          working_directory: recipes/angularjs-ng-file-upload
      - run:
          name: e2e suite for recipes/angularjs-ng-file-upload on Electron
          command: npm run test:ci:electron
          working_directory: recipes/angularjs-ng-file-upload

  test-recipes-react-dropzone:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install dependencies
          command: npm install
          working_directory: recipes/react-dropzone
      - run:
          name: e2e suite for recipes/react-dropzone on Chrome
          command: npm run test:ci:chrome
          working_directory: recipes/react-dropzone
      - run:
          name: e2e suite for recipes/react-dropzone on Firefox
          command: npm run test:ci:firefox
          working_directory: recipes/react-dropzone
      - run:
          name: e2e suite for recipes/react-dropzone on Electron
          command: npm run test:ci:electron
          working_directory: recipes/react-dropzone

  test-recipes-react-html5-input:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install dependencies
          command: npm install
          working_directory: recipes/react-html5-input
      - run:
          name: e2e suite for recipes/react-html5-input on Chrome
          command: npm run test:ci:chrome
          working_directory: recipes/react-html5-input
      - run:
          name: e2e suite for recipes/react-html5-input on Firefox
          command: npm run test:ci:firefox
          working_directory: recipes/react-html5-input
      - run:
          name: e2e suite for recipes/react-html5-input on Electron
          command: npm run test:ci:electron
          working_directory: recipes/react-html5-input

  test-recipes-shadow-dom-native:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install dependencies
          command: npm install
          working_directory: recipes/shadow-dom-native
      - run:
          name: e2e suite for recipes/shadow-dom-native on Chrome
          command: npm run test:ci:chrome
          working_directory: recipes/shadow-dom-native
      - run:
          name: e2e suite for recipes/shadow-dom-native on Firefox
          command: npm run test:ci:firefox
          working_directory: recipes/shadow-dom-native
      - run:
          name: e2e suite for recipes/shadow-dom-native on Electron
          command: npm run test:ci:electron
          working_directory: recipes/shadow-dom-native

workflows:
  version: 2
  production:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - install
      - test:
          requires:
            - install
      - test-recipes-angularjs-ng-file-upload:
          requires:
            - test
      - test-recipes-react-dropzone:
          requires:
            - test
      - test-recipes-react-html5-input:
          requires:
            - test
      - test-recipes-shadow-dom-native:
          requires:
            - test
