# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  cypress: cypress-io/cypress@1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:14.3.0-browsers

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/repo
          paths: [.]
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Source code linting
          command: npm run lint
      # - run:
      #     name: Tests for react-html5-input
      #     command: cd recipes/react-html5-input && npm install && npm run test:ci
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Create app bundle
          command: npm run build
  deploy-recipes:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy recipes/angularjs-ng-file-upload
          command: cd recipes/angularjs-ng-file-upload && npm install && npm run deploy
      - run:
          name: Deploy recipes/react-dropzone
          command: cd recipes/react-dropzone && npm install && npm run deploy
      - run:
          name: Deploy recipes/react-html5-input
          command: cd recipes/react-html5-input && npm install && npm run deploy

workflows:
  version: 2
  test-build-and-publish:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
      - deploy-recipes:
          requires:
            - install
          filters:
            branches:
              only: master
