# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  cypress: cypress-io/cypress@1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cypress/browsers:node13.6.0-chrome80-ff72

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run:
          name: Source code linting
          command: npm run lint
      - run:
          name: Tests for react-html5-input
          command: cd recipes/react-html5-input && npm install && npm run test:ci
      - persist_to_workspace:
          root: ~/repo
          paths: [.]
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Create app bundle
          command: npm run build

workflows:
  version: 2
  test-build-and-publish:
    jobs:
      - test
      - build:
          requires:
            - test
